name: Github Actions Typescript Standard
on: [push, pull_request]
jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.STANDARDS_TOKEN }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          sudo chown -R $USER /usr/local
          npm uninstall typescript --no-save
          npm uninstall tslint --no-save
          npm install
      - name: Run Tests
        run: npm run test
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
      - name: Check coverage
        run: node request.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CORRECT_COVERAGE: ${{ vars.CORRECT_COVERAGE }}
      - name: Upstream to Standards
        env:
          GH_TOKEN: ${{ secrets.STANDARDS_TOKEN }}
          COVERAGE_SOURCE_FILE: ${{ secrets.COVERAGE_SOURCE_FILE }}
        if: ${{ github.event_name == 'push'}}
        run: |
          wget --header "Authorization: token ${GH_TOKEN}" \
          --header "Accept: application/vnd.github.v3.raw" \
          https://api.github.com/repos/codecov/standards/contents/upstream.sh
          bash upstream.sh
